//Criando base de dados dos filmes
//Cada filme tera as seguintes informacoes - titulo, ano, lugar, cena, imagem, texto alt da cena, referencia de onde foi tirada a imagem, latitude e longitude
let following = {titulo: "Following", ano: 1998, lugar: "Londres, Inglaterra", cena: "Uma cena marcante mostra Bill seguindo Cobb pelas ruas de Soho. O ambiente movimentado reflete o tom noir do filme e a obsessão crescente de Bill.", latitude: 51.5152613312499, longitude: -0.136188176988862, imagem: "images/following.png", alt: "Uma pessoa parada na rua com uma motocicleta estacionada na beira da estrada.", fonte: "fonte:https://64.media.tumblr.com/285c3492f348d9b5f21de11a82306f17/tumblr_o0pgzhuYzZ1tus777o1_1280.png"}; 
let amnesia = {titulo: "Amnésia", ano: 2000, lugar: "Los Angeles, Califórnia", cena: "A Travel Inn, que aparece como Discount Inn, é onde Leonard fica hospedado. Muitas cenas foram gravadas em seu quarto, um dos principais cenários.", latitude: 34.2495174071218, longitude: -118.290245010704, imagem: "images/memento.png", alt: "Um carro passando por um motel.", fonte: "fonte:https://pbs.twimg.com/media/EfB9wQSXkAAMUFx?format=jpg&name=900x900"};
let insonia= {titulo: "Insônia", ano: 2002, lugar: "Colúmbia Britânica, Canadá", cena: "A cena em que Will Dormer (Al Pacino) persegue Walter Finch (Robin Williams) e acaba em uma luta no lago Strohn. Essa cena, localizada no Bear Glacier Provincial Park, é crucial para o desfecho do filme. O local é desolado e transmite bem a sensação de isolamento e tensão. Vale a pena visitar pela beleza natural da região.", latitude: 56.1084572210782, longitude: -129.676072199075, imagem: "images/imsomina.png", alt: "Uma pessoa caminhando na chuva em direção a uma cabana nas montanhas.", fonte: "fonte:https://www.imdb.com/title/tt0278504/mediaviewer/rm4179704832/?ref_=ttmi_mi_all_96"};
let batmanbegins = {titulo: "Batman Begins", ano: 2005, lugar: "Chicago, EUA", cena: "A perseguição do Batmóvel em Lower Wacker Drive é icônica. Vale a pena pela arquitetura subterrânea de Chicago e as ruas que criam o clima sombrio de Gotham.", latitude: 41.8869384077735, longitude: -87.6274576597883, imagem: "images/batman-begins.png", alt: "O carro do Batman em um túnel.", fonte: "fonte:https://d2thvodm3xyo6j.cloudfront.net/media/2019/05/35764dd0acd274cd-600x338.jpg"};
let grande = {titulo: "O grande truque", ano: 2006, lugar: "Los angeles, EUA", cena: "A primeira cena desse filme, onde o personagem realiza o truque de teletransporte, foi filmada no Los Angeles Theatre, em Los Angeles. Além desse local, o filme também utilizou outros teatros da região, como o Palace Theatre e o Belasco Theatre.", latitude: 34.046457546397, longitude: -118.252646358561, imagem: "images/the-prestige.png", alt: "Um mágico de terno e braços abertos.", fonte: "fonte:https://www.imdb.com/title/tt0482571/mediaviewer/rm1310857985/?ref_=ttmi_mi_all_73"};
let batmandk = {titulo: "Batman: O Cavaleiro das Trevas", ano: 2008, lugar: "Hong Kong, China", cena: "A cena da queda do prédio em IFC Tower quando Batman sequestra um executivo é de tirar o fôlego. O local é impressionante e uma atração turística.", latitude: 22.2864, longitude: 114.1596, imagem: "images/batman-dark-knight.png", alt: "Batman parado em uma varanda com vista para uma cidade.", fonte: "fonte:https://m.imdb.com/title/tt0468569/mediaviewer/rm3757352193/?ref_=ext_shr_lnk"};
let origem = {titulo: "A Origem", ano: 2010, lugar: "Paris, França", cena: "A cena dos prédios dobrando em Pont de Bir-Hakeim é uma das mais marcantes. O lugar é turístico, com uma vista belíssima da Torre Eiffel ao fundo.", latitude: 48.8572, longitude: 2.2876, imagem: "images/inception.png", alt: "Uma pessoa em frente a um espelho debaixo de uma ponte.", fonte: "fonte:https://www.imdb.com/title/tt1375666/mediaviewer/rm4024878081/?ref_=ttmi_mi_all_197"};
let batmandkres = {titulo: "Batman: O Cavaleiro das Trevas Ressurge", ano: 2012, lugar: "Pittsburgh, EUA", cena: "A batalha em frente à City Hall, com Bane e a multidão, dá uma sensação épica e foi filmada em frente ao Mellon Institute. Vale a visita pela arquitetura e importância histórica do local.", latitude: 40.4465243901596, longitude: -79.95126910241, imagem: "images/batman-rises.png", alt: "Um veículo militar com fumaça saindo da frente de um prédio.", fonte: "fonte:https://www.imdb.com/title/tt1345836/mediaviewer/rm3591612928/?ref_=ttmi_mi_all_25"};
let interestelar = {titulo: "Interestelar", ano: 2014, lugar: "Islândia", cena: "O planeta de gelo foi filmado em Svínafellsjökull. A paisagem glacial é impressionante e vale a visita por suas incríveis formações geológicas.", latitude: 64.0249320454011, longitude: -16.9342539073031, imagem: "images/interestellar.png", alt: "Um grupo de pessoas em trajes espaciais caminhando em um terreno rochoso.", fonte: "fonte:https://lh3.googleusercontent.com/-JgOweJav-ag/VXfdubIL0fI/AAAAAAABDEM/s2o8T8CipG4/svinafellsjokull-glacier-1%25255B2%25255D.jpg?imgmax=800"};
let dunkirk = {titulo: "Dunkirk", ano: 2017, lugar: "Dunkirk, França", cena: "A evacuação na Dunkirk Beach mostra a tensão da guerra. A praia ainda carrega o peso histórico da Segunda Guerra Mundial e vale ser visitada.", latitude: 51.0496402362407, longitude: 2.38664491240491, imagem: "images/dunkirk.png", alt: "Um grupo de soldados parados na praia.", fonte: "fonte:https://flim-1-0-2.s3.eu-central-1.amazonaws.com/thumbs/thumbnail/a888699e51e611ec9f0310ddb1aba44f.jpeg"};
let tenet = {titulo: "Tenet", ano: 2020, lugar: "Tallinn, Estônia", cena: "A perseguição de carros em Laagna Road é uma das cenas de ação mais intensas. Vale a pena ver a arquitetura brutalista da cidade.", latitude: 59.4442599846644, longitude: 24.8863401045096, imagem: "images/tenet.png", alt: "Uma pessoa em um carro com a porta aberta.", fonte: "fonte:https://hips.hearstapps.com/hmg-prod/images/saab-3-1593185293.jpg?resize=1200:*"};
let oppenheimer = {titulo: "Oppenheimer", ano: 2023, lugar: "Los Alamos, Novo México", cena: "Algumas cenas do filme foram gravadas em Los Alamos, aproveitando a arquitetura e paisagens originais que serviram de cenário para o Projeto Manhattan. A cidade possui diversos pontos turísticos relacionados à história do cientista e da bomba atômica, como a Fuller Lodge, onde Oppenheimer e outros cientistas se reuniam", latitude: 35.8816156375006, longitude: -106.302767786655, imagem: "images/los-alamos.png", alt: "Uma pessoa andando na rua.", fonte: "fonte:https://flim-1-0-2.s3.eu-central-1.amazonaws.com/thumbs/hd_720px/4d8a4ceb8fba11eea46a0612238522d6.jpeg"};

let filmes = [following,
    amnesia,
    insonia,
    batmanbegins,
    grande,
    batmandk,
    origem,
    batmandkres,
    interestelar,
    dunkirk,
    tenet,
    oppenheimer];